name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: ./sketchpad.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  checkout:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

  premake:
    runs-on: windows-latest
    needs: checkout
    
    steps:
    - run: ls -a
      
  build:
    runs-on: windows-latest
    needs: premake

    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
