name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  SOLUTION_FILE: ./sketchpad.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        # configuration: [Debug, Release]
        # platform: [Win32, x64]
        configuration: [Debug]
        platform: [Win32]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    # make sure `vcpkg integrate install` runs after `msbuild` has been added to $PATH
    # note that dependencies are not cached so this can be slow (takes around 10 mins)
    - name: Install Dependencies
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg.exe install assimp

    - name: Run Premake5
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: ./premake.bat

    - name: Build Solution
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} ${{ env.SOLUTION_FILE }}
